import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  Navbar2  from "./navbar-02";




// app/fonts.ts
import { Gilda_Display, Merriweather_Sans } from 'next/font/google';
import Footer8 from "./footer-08";

export const gildaDisplay = Gilda_Display({
  subsets: ['latin'],
  weight: '400', // Adjust if needed
  display: 'swap',
});

export const merriweatherSans = Merriweather_Sans({
  subsets: ['latin'],
  weight: ['400', '700'], // Adjust weights you need
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" w-screen">
      <Navbar2 />
        {children}
        <Footer8 />
      </body>
    </html>
  );
}
